esphome:
  name: boneio-em-v01

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://ell249/esphome-PCT2075@master
    components: [ pct2075 ]

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

uart:
  id: mod_bus
  rx_pin: 3
  tx_pin: 1
  baud_rate: 9600
  stop_bits: 1
  
#modbus:
#  flow_control_pin: 4
#  uart_id: mod_bus
#  id: modbus1
#modbus_controller:
#  - id: sdm
#    address: 0x0001
#    modbus_id: modbus1
#    update_interval: 5s
    
i2c:
  sda: GPIO32
  scl: GPIO33
  scan: True
  frequency: 100kHz

pcf8574:
  - id: 'pcf_1'
    address: 0x21
    pcf8575: true
   
  - id: 'pcf_2'
    address: 0x20
    pcf8575: true

#dallas:
#- pin: GPIO5

logger:
  baud_rate: 0
api:
ota:
web_server:
  port: 80
 
binary_sensor:
  - platform: gpio
    name: "IN_1"
    pin:
      number: 39
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_1

  - platform: gpio
    name: "IN_2"
    pin:
      number: 36
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_2

  - platform: gpio
    name: "IN_3"
    pin:
      number: 15
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_3

  - platform: gpio
    name: "IN_4"
    pin:
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_4

  - platform: gpio
    name: "IN_5"
    pin:
      number: 35
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_5

  - platform: gpio
    name: "IN_6"
    pin:
      number: 17
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_6

    
switch:
    
  - platform: gpio
    id: relay_1
    name: "Relay_01"
    pin:
      pcf8574: pcf_1
      # Use pin number 15
      number: 15
      mode:
        output: true
      inverted: true
  - platform: gpio
    id: relay_2
    name: "Relay_02"
    pin:
      pcf8574: pcf_1
      # Use pin number 14
      number: 14
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_3
    name: "Relay_03"
    pin:
      pcf8574: pcf_1
      # Use pin number 13
      number: 13
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_4
    name: "Relay_04"
    pin:
      pcf8574: pcf_1
      # Use pin number 12
      number: 12
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_5
    name: "Relay_05"
    pin:
      pcf8574: pcf_1
      # Use pin number 11
      number: 11
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_6
    name: "Relay_06"
    pin:
      pcf8574: pcf_1
      # Use pin number 10
      number: 10
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: relay_7
    name: "Relay_07"
    pin:
      pcf8574: pcf_1
      # Use pin number 9
      number: 9
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_8
    name: "Relay_08"
    pin:
      pcf8574: pcf_1
      # Use pin number 8
      number: 8
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: relay_9
    name: "Relay_09"
    pin:
      pcf8574: pcf_2
      # Use pin number 15
      number: 15
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_10
    name: "Relay_10"
    pin:
      pcf8574: pcf_2
      # Use pin number 14
      number: 14
      mode:
        output: true
      inverted: true
  
  - platform: gpio
    id: relay_11
    name: "Relay_11"
    pin:
      pcf8574: pcf_2
      # Use pin number 13
      number: 13
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_12
    name: "Relay_12"
    pin:
      pcf8574: pcf_2
      # Use pin number 12
      number: 12
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_13
    name: "Relay_13"
    pin:
      pcf8574: pcf_2
      # Use pin number 11
      number: 11
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_14
    name: "Relay_14"
    pin:
      pcf8574: pcf_2
      # Use pin number 10
      number: 10
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_15
    name: "Relay_15"
    pin:
      pcf8574: pcf_2
      # Use pin number 9
      number: 9
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_16
    name: "Relay_16"
    pin:
      pcf8574: pcf_2
      # Use pin number 8
      number: 8
      mode:
        output: true
      inverted: true
    
  - platform: gpio
    id: relay_17
    name: "Relay_17"
    pin:
      pcf8574: pcf_1
      # Use pin number 0
      number: 0
      mode:
        output: true
      inverted: true

  - platform: gpio
    id: relay_18
    name: "Relay_18"
    pin:
      pcf8574: pcf_1
      # Use pin number 1
      number: 1
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_19
    name: "Relay_19"
    pin:
      pcf8574: pcf_1
      # Use pin number 2
      number: 2
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_20
    name: "Relay_20"
    pin:
      pcf8574: pcf_1
      # Use pin number 3
      number: 3
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_21
    name: "Relay_21"
    pin:
      pcf8574: pcf_1
      # Use pin number 4
      number: 4
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_22
    name: "Relay_22"
    pin:
      pcf8574: pcf_1
      # Use pin number 5
      number: 5
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_23
    name: "Relay_23"
    pin:
      pcf8574: pcf_1
      # Use pin number 6
      number: 6
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_24
    name: "Relay_24"
    pin:
      pcf8574: pcf_1
      # Use pin number 7
      number: 7
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_25
    name: "Relay_25"
    pin:
      pcf8574: pcf_2
      # Use pin number 0
      number: 0
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_26
    name: "Relay_26"
    pin:
      pcf8574: pcf_2
      # Use pin number 1
      number: 1
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_27
    name: "Relay_27"
    pin:
      pcf8574: pcf_2
      # Use pin number 2
      number: 2
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_28
    name: "Relay_28"
    pin:
      pcf8574: pcf_2
      # Use pin number 3
      number: 3
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_29
    name: "Relay_29"
    pin:
      pcf8574: pcf_2
      # Use pin number 4
      number: 4
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_30
    name: "Relay_30"
    pin:
      pcf8574: pcf_2
      # Use pin number 5
      number: 5
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_31
    name: "Relay_31"
    pin:
      pcf8574: pcf_2
      # Use pin number 6
      number: 6
      mode:
        output: true
      inverted: true
      
  - platform: gpio
    id: relay_32
    name: "Relay_32"
    pin:
      pcf8574: pcf_2
      # Use pin number 7
      number: 7
      mode:
        output: true
      inverted: true


sensor:
  - platform: pct2075
    temperature:
     id: led_temp
     name: "LM75B Temperature"
    update_interval: 30s

  # example modbus
#  - platform: sdm_meter
#    phase_a:
#      current:
#        name: "SDM230M Current"
#      voltage:
#        name: "SDM230M Voltage"
#      active_power:
#        name: "SDM230M Power"
#      power_factor:
#        name: "SDM230M Power Factor"
#      apparent_power:
#        name: "SDM230M Apparent Power"
#      reactive_power:
#        name: "SDM230M Reactive Power"
#      phase_angle:
#        name: "SDM230M Phase Angle"
#    frequency:
#      name: "SDM230M Frequency"
#    total_power:
#      name: "SDM230M Total Power"
#    import_active_energy:
#      name: "SDM230M Import Active Energy"
#    export_active_energy:
#      name: "SDM230M Export Active Energy"
#    import_reactive_energy:
#      name: "SDM230M Import Reactive Energy"
#    export_reactive_energy:
#      name: "SDM230M Export Reactive Energy"
#    update_interval: 60s  

  # example dallas
#  - platform: dallas
#    address: 
#   name: "Dallas Sensor 1"
    
  
    
